### ISSUE TITLE
Examples in Readme

### ISSUE THREAD

**Issue by dnaber-de** [bueltge/wp-rest-api-filter-items#1]
The current Readme shows this as an example:

> #### Result for post, `wp-json/posts?items=ID,title,content`
> 
> ``` json
> [
>   {
>     "ID": 1,
>     "title": "Hello world!",
>     "content": "<p>Welcome to <a href=\"http:\/\/localhost\/wpbeta\/\">WP Beta Dev Sites<\/a>. This is your first post. Edit or delete it, then start blogging!<\/p>\n",
>     "author": {...},
>     "featured_image": null,
>     "terms": {...}
>   }
> ]
> ```
> 
> But the fields `author`, `featured_image` and `terms` should not appear in the example output, shouldn't they?

**Comment by bueltge** [comment]
This not so easy. The API add this values via hook, is not in the array to filter. I have add a idea, but I'm not very happy with this. :(

**Comment by bueltge** [comment]
Now used in the [branch wp-api-v1](https://github.com/bueltge/WP-REST-API-Filter-Items/tree/wp-api-v1), releases with 9d43ba24fada128820fa0d0878b54dad67fa9f05.
