### ISSUE TITLE
Incompatibility issue for beta > 11

### ISSUE THREAD

**Issue by enricodeleo** [bueltge/wp-rest-api-filter-items#3]
Upgrading to version 12 or 13 breaks this plugin features. I haven't figured out why. Any ideas?

**Comment by bueltge** [comment]
Do you have read the readme? The master branch is on development for wp api 2.+ and should not work. 
Only the old stable version in the other branch works your only with wp api 1.+. The plugin was created for a customer, there use currently always the WP api 1.0 and the development on the new version is currently on sleeping, to less time. 
Pull requests are welcome. 
Best.

**Comment by enricodeleo** [comment]
Yes, I read that the master branch is a refactoring for v2. And I confirm that it works on v2 <= beta11.
I thought I could report that it works perfectly until beta 11 and I was just wondering if there were someone who noticed the break on subsequent versions and had ideas about it.
Sorry if somehow I opened an unnecessary or junk issue.

**Comment by bueltge** [comment]
I haven't tested with v2. I think it can't work, other nameshema. But the plugin is helpful, maybe I found later time to fix this topic. I will also check on beta 11, the difference from smaller beta 11 and beta 11 is currently not clear for me.

> Sorry if somehow I opened an unnecessary or junk issue.

No worries, it is a issue and it easy to closed, but the fix is more helpful ;)

**Comment by bueltge** [comment]
PLease test the new version, it should fixed this problem.
I have tested with API v2 Beta 13. The hook was changes :(

committed with b85f8f4a2ddf22120002d261ba62a8624bd6f9ce
Thanks for your feedback.
