### ISSUE TITLE
is it possible to filter posts with date feilds by comparing ?

### ISSUE THREAD

**Issue by santoshgistto** [bueltge/wp-rest-api-filter-items#4]
Ex:
custom_start_date = “in milliseconds”,
custom_end_date = “in milliseconds”

**Comment by bueltge** [comment]
Hey.
no, the filter use only keys, data fields.
A comparison ist currently not possible.

Best.

**Comment by santoshgistto** [comment]
ok thanks for response, is there any alternate solution?

**Comment by bueltge** [comment]
Sorry, I don't know a altertnative. Maybe you ask on [WP StackExchange](http://wordpress.stackexchange.com/)
