### ISSUE TITLE
some help 

### ISSUE THREAD

**Issue by irshad2809** [bueltge/wp-rest-api-filter-items#5]
`http://localhost/wordpress/wp-json/wp/v2/posts/8095?items=_links`
i am trying to get only "_links " but i get empty [] in response ,

**Comment by bueltge** [comment]
What is `_links`? The plugin filter only for fields of the post type, like title, ID, ... 
Maybe you field is from the meta data, then it is not possible to filter for each meta value, field.

**Comment by irshad2809** [comment]
thanks for quick reponse.
