### ISSUE TITLE
Not working in Woocommerce

### ISSUE THREAD

**Issue by iiKulakov** [bueltge/wp-rest-api-filter-items#7]
Query: 
`site.com/wp-json/wc/v3/products?items=id,name`
just outputs all fields.

This query is working: 
`site.com/wp-json/wp/v2/comments?items=id,author_name`

Is there a way to fix it?

**Comment by bueltge** [comment]
@iiKulakov WooCommerce use a custom url, api - `site.com/wp-json/wc/` . This plugin supports currently only the default WP REST API, like `site.com/wp-json/wp/`. But Pull Request, Ideas are really welcome!
